#!/bin/bash


outfile=dist/bake
mkdir -p dist

echo "\
#!/bin/bash
# bake - Bash Make - v`cat VERSION` - https://github.com/fengb/bake

" >$outfile

find src -type f | while read file; do
  cat "$file" >>$outfile
done
chmod +x $outfile
